spring:
  datasource:
    url: jdbc:mysql://localhost:3306/jpa?serverTimezone=GMT%2B8&characterEncoding=utf-8&rewriteBatchedStatements=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    separator: $
    initialization-mode: always
    schema: classpath:sql/jpa-schema.sql
    data: classpath:sql/jpa-data.sql